version: '3.1'

services:
  db:
    image: mysql
    env_file:
      - .env
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "${MYSQL_PORT}:3306"