version: '3.1'

services:
  db: 
    image: mysql
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE:
    ports:
      - "${MYSQL_PORT}:3306"